### ISSUE TITLE
[FR] 惊喜的看到在向下兼容

### ISSUE THREAD

**Issue by smgfw** [vrichv/my-tv-0#1]
（https://github.com/yaoxieyoulei/mytv-android/issues/42#issuecomment-2249269303）

> > 开心了一下 mytv0也支持4.x了，帅不过两秒，又不开心了4.4以上。。😄我的小米电视2是安卓4.3😳

> 代码理论上4.2以上完全没有问题，你只需要动动小手，修改个依赖和api版本就能编译出来了 只是这些老旧设备有很多诡异的问题，搞起来超级烦躁，没设备调试不想兼容

我看增加了ijk和jb版，那个jb写着4.1/4.2，是只适配4.1和4.2，不适配4.3吗？

**Comment by vrichv** [comment]
写错了，api17+就是4.2/4.3

**Comment by smgfw** [comment]
> 写错了，api17+就是4.2/4.3

用上了，还不错，非常感谢。
现在遇到的问题是：配置地址的端口总是在变。按说不应该啊，不知道是不是mytv0的有意设计？
