### ISSUE TITLE
[BUG] 反应几个bug

### ISSUE THREAD

**Issue by dxxjg** [vrichv/my-tv-0#3]
### 检查清单

- [X] 明白上述声明
- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

ps：我是4.3，清楚作者关于JB的声明。发现的问题也提交一下，供开发者筛查😄

- [ ] 频道列表页，遥控器下翻速度如果太快，会丢失焦点，多次复现。
- [ ] 偶发性丢失10086端口，仅出现过一次。未复现。
- [ ] 推送直播源时，出现过多种状况：1️⃣无响应，退出再开依然未成功。2️⃣响应迟钝，继续看一会儿可能会出现提示“导入成功”。3️⃣响应导入成功后，但是无法上下换台，也无法唤出列表。（最近在梳理测试直播源，所以频繁使用推送功能，可以算作是 非正常使用情景）

**Comment by vrichv** [comment]
源导入这块有比较多问题，估计要大改，看lizongying大神有没有时间修复。
后续没有大问题，家里老人有得看我这边不打算继续魔改了
纯纯的为爱发电，太累

**Comment by dxxjg** [comment]
> 源导入这块有比较多问题，估计要大改，看lizongying大神有没有时间修复。 后续没有大问题，家里老人有得看我这边不打算继续魔改了 纯纯的为爱发电，太累

明白，看后续吧，目前用着挺好，谢谢大佬。
