### ISSUE TITLE
[BUG] ErrorCode 2000

### ISSUE THREAD

**Issue by lon91ong** [vrichv/my-tv-0#5]
### 检查清单

- [X] 明白上述声明
- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

盒子是移动魔百盒cm201-2, 安装完全默认设置
错误信息如下图
![IMG_20240810_203041](https://github.com/user-attachments/assets/5852b6ed-422e-4a06-b895-a702fdb9a369)

不清楚是**内置源**的问题还是需要**ipv6网络支持**的问题

### 预期行为

正常播放

### 实际行为

报错无法播放

### UI / OS

移动魔百盒cm201-2

### Android 版本

4.4

**Comment by vrichv** [comment]
自行寻找可用的节目源
