### ISSUE TITLE
[BUG] 移动网络下报网络异常

### ISSUE THREAD

**Issue by dz515704201** [vrichv/my-tv-0#7]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

1.3.7

### 電視品牌

小米

### Android版本

4.2

### 問題描述

移动网络下一直报网络异常[2001],能适配下移动版本吗。客厅还有一台电视用的原版的ipv6蛮好。网络是没问题的

**Comment by vrichv** [comment]
非bug，自行换可用的源
